// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTablesToTask(arg1, arg2) {
  return window['go']['backend']['App']['AddTablesToTask'](arg1, arg2);
}

export function AnalyzeTables(arg1) {
  return window['go']['backend']['App']['AnalyzeTables'](arg1);
}

export function CancelTableAnalysis(arg1, arg2) {
  return window['go']['backend']['App']['CancelTableAnalysis'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['backend']['App']['CancelTask'](arg1);
}

export function ConnectDatabase(arg1) {
  return window['go']['backend']['App']['ConnectDatabase'](arg1);
}

export function CreateTask(arg1, arg2) {
  return window['go']['backend']['App']['CreateTask'](arg1, arg2);
}

export function DeleteAnalysisResult(arg1) {
  return window['go']['backend']['App']['DeleteAnalysisResult'](arg1);
}

export function DeleteDatabaseConnection(arg1) {
  return window['go']['backend']['App']['DeleteDatabaseConnection'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['backend']['App']['DeleteTask'](arg1);
}

export function GetAllConnectionsWithMetadata() {
  return window['go']['backend']['App']['GetAllConnectionsWithMetadata']();
}

export function GetAllTasks() {
  return window['go']['backend']['App']['GetAllTasks']();
}

export function GetAnalysisResults(arg1) {
  return window['go']['backend']['App']['GetAnalysisResults'](arg1);
}

export function GetAvailableRules() {
  return window['go']['backend']['App']['GetAvailableRules']();
}

export function GetDatabaseConnections() {
  return window['go']['backend']['App']['GetDatabaseConnections']();
}

export function GetEnhancedAnalysisResult(arg1, arg2) {
  return window['go']['backend']['App']['GetEnhancedAnalysisResult'](arg1, arg2);
}

export function GetMetadataColumns(arg1) {
  return window['go']['backend']['App']['GetMetadataColumns'](arg1);
}

export function GetMetadataTables(arg1) {
  return window['go']['backend']['App']['GetMetadataTables'](arg1);
}

export function GetTableAnalysisResult(arg1, arg2) {
  return window['go']['backend']['App']['GetTableAnalysisResult'](arg1, arg2);
}

export function GetTableSelections() {
  return window['go']['backend']['App']['GetTableSelections']();
}

export function GetTables() {
  return window['go']['backend']['App']['GetTables']();
}

export function GetTablesMetadata(arg1) {
  return window['go']['backend']['App']['GetTablesMetadata'](arg1);
}

export function GetTaskStatus(arg1) {
  return window['go']['backend']['App']['GetTaskStatus'](arg1);
}

export function GetTaskTables(arg1) {
  return window['go']['backend']['App']['GetTaskTables'](arg1);
}

export function GetTasksByDatabase(arg1) {
  return window['go']['backend']['App']['GetTasksByDatabase'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function LogFrontendAction(arg1, arg2, arg3) {
  return window['go']['backend']['App']['LogFrontendAction'](arg1, arg2, arg3);
}

export function RemoveTableFromTask(arg1, arg2) {
  return window['go']['backend']['App']['RemoveTableFromTask'](arg1, arg2);
}

export function SaveDatabaseConnection(arg1) {
  return window['go']['backend']['App']['SaveDatabaseConnection'](arg1);
}

export function SaveTableSelections(arg1) {
  return window['go']['backend']['App']['SaveTableSelections'](arg1);
}

export function StartAnalysisTasks(arg1, arg2) {
  return window['go']['backend']['App']['StartAnalysisTasks'](arg1, arg2);
}

export function StartTaskAnalysis(arg1) {
  return window['go']['backend']['App']['StartTaskAnalysis'](arg1);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['backend']['App']['TestDatabaseConnection'](arg1);
}

export function UpdateDatabaseMetadata(arg1) {
  return window['go']['backend']['App']['UpdateDatabaseMetadata'](arg1);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateTask'](arg1, arg2, arg3);
}
