// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTablesToTask(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function AnalyzeTables(arg1:Array<string>):Promise<Array<any>>;

export function CancelTableAnalysis(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CancelTask(arg1:string):Promise<void>;

export function ConnectDatabase(arg1:backend.DatabaseConfig):Promise<string>;

export function CreateTask(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteAnalysisResult(arg1:string):Promise<void>;

export function DeleteDatabaseConnection(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<Record<string, any>>;

export function GetAllConnectionsWithMetadata():Promise<Array<Record<string, any>>>;

export function GetAllTasks():Promise<Array<Record<string, any>>>;

export function GetAnalysisResults(arg1:string):Promise<Array<Record<string, any>>>;

export function GetAvailableRules():Promise<Array<string>>;

export function GetDatabaseConnections():Promise<Array<backend.DatabaseConfig>>;

export function GetEnhancedAnalysisResult(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetMetadataColumns(arg1:string):Promise<Array<Record<string, any>>>;

export function GetMetadataTables(arg1:string):Promise<Array<Record<string, any>>>;

export function GetTableAnalysisResult(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetTableSelections():Promise<Array<string>>;

export function GetTables():Promise<Array<string>>;

export function GetTablesMetadata(arg1:Array<string>):Promise<Record<string, Record<string, any>>>;

export function GetTaskStatus(arg1:string):Promise<Record<string, any>>;

export function GetTaskTables(arg1:string):Promise<Array<Record<string, any>>>;

export function GetTasksByDatabase(arg1:string):Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function LogFrontendAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RemoveTableFromTask(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SaveDatabaseConnection(arg1:backend.DatabaseConfig):Promise<void>;

export function SaveTableSelections(arg1:Array<string>):Promise<void>;

export function StartAnalysisTasks(arg1:string,arg2:Array<string>):Promise<string>;

export function StartTaskAnalysis(arg1:string):Promise<Record<string, any>>;

export function TestDatabaseConnection(arg1:backend.DatabaseConfig):Promise<string>;

export function UpdateDatabaseMetadata(arg1:string):Promise<Record<string, any>>;

export function UpdateTask(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;
